default_language_version:
  python: python3
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-toml
      - id: check-case-conflict
      - args:
          - --maxkb=10000
        id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
  - hooks:
      - id: ruff
      - id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
  - hooks:
      - args:
          - --py312-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
  - hooks:
      - args:
          - --verbose
          - --fail-under=80
          - --ignore-init-module
          - --ignore-init-method
          - --ignore-module
          - --ignore-nested-functions
          - -vv
        id: interrogate
    repo: https://github.com/econchick/interrogate
    rev: 1.7.0

  - hooks:
      - id: shellcheck
    repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2

  - hooks:
      - additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
        args:
          - --number
        id: mdformat
    repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16

  - hooks:
      - args:
          - --skip=logs/**,data/**,*.ipynb,*.csv,pixi.lock,*.jsonl,.git/*
        id: codespell
    repo: https://github.com/codespell-project/codespell
    rev: v2.2.4

  - hooks:
      - id: nbstripout
    repo: https://github.com/kynan/nbstripout
    rev: 0.6.1

  # - hooks:
  #     - id: nbqa-ruff
  #   repo: https://github.com/nbQA-dev/nbQA
  #   rev: 1.8.7

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            build,
            chore,
            ci,
            docs,
            feat,
            fix,
            perf,
            refactor,
            revert,
            style,
            test,
            results,
            analysis,
          ]
