name: "academia-fyi"
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - nodejs=20
  - pnpm=9.1.1

  - jupyter=1
  - ipython=8
  - pandas=2
  - numpy=1
  - scipy=1
  - openpyxl=3
  - tldextract=5

  - mypy=1.10
  - black=24.4
  - pre-commit=3.7